### ISSUE TITLE
Implement cross table constraints

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/isomorphicdb#16]
* [ ] Primary Key
* [ ] Unique
* [ ] Foreign Key

Test cases:
* [ ] create table with FK to PK on another table
* [ ] create table with FK to neither PK nor Unique column on another table
* [ ] Multiple columns PK
* [ ] Multiple columns Unique
* [ ] Multiple columns FK
* [ ] FK with wrong reference type
