### ISSUE TITLE
Support different SQL types

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/isomorphicdb#17]
* [x] integer types `smallint`, `integer` and `bigint` #77
* [x] character string types `char(n)` and `varchar(n)` #89 
* [x] `boolean` type #107
* [ ] numeric types `decimal(p, s)` and its alias `numeric(p, s)` #90 
* [x] approximate types `real` and `double precision` #91 
* [ ] date time types `time [without timezone]`, `time with timezone`, `timestamp [without timezone]`, `timestamp with timezone` and `date`
* [ ] time interval #93
