### ISSUE TITLE
Evaluation of binary operations

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/isomorphicdb#489]
* [x] Support Binary Addition operation #519 
* [x] Support Binary Subtraction operation #518 
* [x] Support Binary Multiplication operation #517 
* [x] Support Binary Division operation #516 
* [x] Support Binary Modulus operation #515 
* [x] Support Binary Bitwise Xor operation #514 
* [x] Support Binary Bitwise Or operation #513 
* [x] Support Binary Bitwise And operation #512 
* [x] Support Binary Exponent operation #511 
* [x] Support Binary Strings Concatenation operation #510
* [ ] Support Binary Comparison operations #509 
* [x] Support Binary Logical And operation #508 
* [x] Support Binary Logical Or operation #507 
* [x] Support Binary Like and Not Like operations #506 
* [x] Support Binary Bitwise Shifts operations #505
