### ISSUE TITLE
Evaluation of unary operations

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/isomorphicdb#490]
* [x] Support Unary Minus operation #491 
* [x] Support Unary Plus operation #492 
* [x] Support Unary Not operation #493  
* [x] Support Unary Bitwise Not operation #494  
* [x] Support Unary Square Root operation #495 
* [x] Support Unary Cube Root operation #496 
* [x] Support Unary Factorial operation #497 
* [x] Support Unary Abs operation #498
